
USE study;

DROP TABLE IF EXISTS vimrc_zq;
CREATE TABLE vimrc_zq (
	id INT AUTO_INCREMENT NOT NULL,
	path VARCHAR(255),
	s VARCHAR(255),
	PRIMARY KEY(id),
	UNIQUE KEY(id)
) DEFAULT CHARSET ="UTF8";

